title: Блог Олега Стрижеченко
email: oleg.strizhechenko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  30% личного, 20% linux, 30% наблюдения за разработкой, 5% книги, 10% математика и статистика, 10% шуток
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://strizhechenko.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: strizhechenko

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
